Repository codersforcauses/wadl, pull requests merged in 2022-12, with the labels that each got.

#30 Issue 17: Install Pinia
  package.json
  yarn.lock
Labels: frontend

#27 I8 create navbar component
  app.vue
  assets/logos/ShortLogo.png
  assets/logos/TextlessLogo.png
  assets/logos/TextlessLogoYellow-Black.png
  assets/logos/TextlessLogoYellow.png
  assets/logos/TextlessTransparentLogo.png
  assets/logos/TransparentLongLogo.png
  components/NavBar.vue
  components/NavBar/HomeButton.vue
  components/NavBar/LoginButton.vue
  components/NavBar/NavBar.vue
  layouts/default.vue
  pages/index.vue
Labels: frontend

#36 I34 Create Manage Adjudicators Page
  components/Header/index.vue
  components/SearchBar/index.vue
  data/adjudicators.json
  nuxt.config.js
  package.json
  pages/adjudicators.vue
  tailwind.config.js
  yarn.lock
Labels: frontend

#44 I39 Create Button Component
  components/Button/index.vue
  components/Header/index.vue
  components/SearchBar/index.vue
  pages/adjudicators.vue
  pages/components.vue
Labels: frontend

#60 revert node version
  Firebase/functions/package.json
Labels: bug

#66 file drop!
  docs/docs/first-page.md
  docs/docs/images/ShortLogo.png
  docs/docs/images/TextlessLogo.png
  docs/docs/images/TextlessLogoYellow-Black.png
  docs/docs/images/TextlessLogoYellow.png
  docs/docs/images/TextlessTransparentLogo.png
  docs/docs/images/TransparentLongLogo.png
  docs/docs/index.md
  docs/docs/installation-guide.md
  docs/mkdocs.yml
  docs/requirements.txt
Labels: documentation, enhancement, difficulty::hard

#59 I38 create manage institution page
  data/institutions.json
  pages/institutions.vue
Labels: frontend

#67 I12 super admin page
  components/Header/index.vue
  components/HomePage/LevelButton.vue
  components/admin/AdminButton.vue
  components/admin/ProfileInfo.vue
  pages/adjudicators.vue
  pages/admin.vue
  pages/index.vue
  yarn.lock
Labels: frontend, good first issue, difficulty::easy, priority::high

#83 I73 Pinia user store
  components/FormField/index.vue
  components/SignUpForm/DefaultInputs.vue
  components/SignUpForm/Form.vue
  components/SignUpForm/Roles.vue
  components/SignUpForm/index.vue
  nuxt.config.js
  package.json
  pages/admin/adjudicators.vue
  pages/admin/index.vue
  pages/admin/institutions.vue
  pages/components.vue
  pages/signup.vue
  stores/user.js
  yarn.lock
Labels: frontend

#91 i80 Update Button Component with Size Prop
  components/Button/index.vue
  pages/admin/index.vue
  pages/admin/signup-requests.vue
  pages/components.vue
  tailwind.config.js
Labels: frontend

#109 I84 update navbar UI
  Firebase/firestore.rules
  components/NavBar/LoginButton.vue
  components/NavBar/NavBar.vue
  pages/login.vue
  stores/user.js
  tailwind.config.js
Labels: frontend
