Repository codersforcauses/wadl, pull requests merged in 2023-02, with the labels that each got.

#228 189 Added dropdown component
  components/Dropdown.vue
  components/Select.vue
  pages/admin/signup-requests.vue
  pages/components.vue
  pages/signup.vue
Labels: frontend

#233 232 Team Functionality
  pages/admin/index.vue
  pages/admin/teams.vue
Labels: frontend

#258 I153 Add Component Documentation
  docs/docs/components.md
  docs/docs/first-page.md
  docs/docs/using-mkdocs.txt
  docs/mkdocs.yml
  docs/requirements.txt
Labels: documentation, difficulty:extreme

#253 I241 Team Coordinator Documentation
  docs/docs/user-guide.md
  docs/mkdocs.yml
Labels: documentation

#244 I231 fill in the rest of the team coordinator pages
  components/NavBar/NavBar.vue
  pages/coordinator/changepassword.vue
  pages/coordinator/userinformation.vue
  stores/user.js
Labels: backend, frontend

#266 I219 implement email service in backend
  Firebase/dummyData/auth_export/accounts.json
  Firebase/dummyData/firebase-export-metadata.json
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/output-0
  Firebase/dummyData/firestore_export/firestore_export.overall_export_metadata
  Firebase/dummyData/storage_export/buckets.json
  Firebase/extensions/firestore-send-email.env
  Firebase/firebase.json
  Firebase/functions/yarn.lock
  middleware/logged-in.global.js
  misc/firebaseHelpers.js
  pages/admin/create-admin.vue
  pages/login.vue
  pages/resetpassword.vue
  pages/signup.vue
  server/api/create-admin.post.js
  server/api/send-email.post.js
  stores/admin.js
  stores/user.js
  yarn.lock
Labels: backend

#247 I173 add delete buttons
  pages/admin/institutions.vue
  pages/admin/tournaments/index.vue
  pages/admin/venues.vue
  stores/institutions.js
  stores/tournaments.js
  stores/venues.js
Labels: enhancement, frontend, difficulty::medium, priority::low, stage 2

#277 I250 create manage divisions page
  Firebase/firestore.rules
  components/Button.vue
  components/Chip.vue
  components/Division/DivisionPanel.vue
  components/Dropdown.vue
  components/Frame.vue
  components/Header.vue
  pages/admin/tournaments/[tournamentId]/division/[level].vue
  pages/admin/tournaments/[tournamentId]/index.vue
  stores/teams.js
  stores/tournaments.js
  stores/venues.js
Labels: backend, frontend

#280 I240 create stepper component
  components/Stepper.vue
  pages/admin/tournaments/[tournamentId]/index.vue
  pages/components.vue
Labels: frontend, difficulty::medium, priority::high

#285 Added school field and display in table
  pages/admin/signup-requests.vue
  pages/signup.vue
  stores/admin.js
  stores/user.js
Labels: frontend

#286 263 Additional Documentation
  docs/docs/images/firebaselogo.png
  docs/docs/images/nuxtlogo.png
  docs/docs/index.md
  docs/docs/installation-guide.md
Labels: documentation

#284 I262 add documentation for admin users
  docs/docs/tournament-setup.md
  docs/mkdocs.yml
Labels: documentation
