Repository codersforcauses/wadl, pull requests merged in 2023-01, with the labels that each got.

#114 I68 research and implement how to dump dummy data effectively into firebase emulators
  Firebase/.gitignore
  package.json
  yarn.lock
Labels: backend, enhancement

#125 I104 add phone number to registration form
  components/SignUpForm/index.vue
  pages/login.vue
  stores/user.js
Labels: frontend

#90 I69 auto deploy documentation workflow
  .github/workflows/main.yml
Labels: documentation, enhancement, good first issue, difficulty::easy, priority::high, MVP

#99 I10 create team coordinator page
  components/Coordinator/Table.vue
  data/teams.json
  pages/coordinator.vue
  yarn.lock
Labels: frontend, difficulty::easy, priority::high

#137 I134 create admin users page
  components/SignUpForm/index.vue
  package-lock.json
  pages/admin/create-admin.vue
  pages/admin/index.vue
  pages/login.vue
  stores/admin.js
  stores/user.js
  tailwind.config.js
Labels: backend, frontend

#129 Documentation page reshuffle
  .github/workflows/main.yml
  docs/docs/first-page.md
  docs/docs/images/ShortLogo.png
  docs/docs/images/TextlessLogo.png
  docs/docs/images/TextlessLogoYellow-Black.png
  docs/docs/images/TextlessLogoYellow.png
  docs/docs/images/TextlessTransparentLogo.png
  docs/docs/images/TransparentLongLogo.png
  docs/docs/index.md
  docs/docs/installation-guide.md
  docs/mkdocs.yml
  docs/requirements.txt
Labels: documentation

#138 I13 Create new tournament modal
  components/Chip/index.vue
  components/Modal/Modal.vue
  components/Multiselect/index.vue
  components/SearchBar/index.vue
  components/Table/index.vue
  components/Venues/Modal.vue
  data/tournaments.json
  pages/admin/institutions.vue
  pages/admin/tournaments.vue
  pages/components.vue
  stores/tournaments.js
Labels: frontend

#144 I140 added admin button to nav bar
  components/NavBar/NavBar.vue
Labels: frontend

#151 Added top margin to profileInfo + user variable in admin page
  components/admin/ProfileInfo.vue
  pages/admin/index.vue
Labels: frontend, difficulty::easy, priority::high

#149 I89 add validation to registration form
  components/FormField/index.vue
  components/SignUpForm/Roles.vue
  components/SignUpForm/index.vue
  yarn.lock
Labels: frontend, difficulty::easy

#156 I136 update login functionality
  Firebase/functions/index.js
  Firebase/functions/requestingState.js
  Firebase/functions/requestingUsers.js
  plugins/3.firebase-functions-emulator.client.js
  stores/auth.js
Labels: backend, enhancement, frontend

#170 i169 fixed deployment issue
  pages/admin/venues.vue
Labels: bug, frontend

#181 I117 team coordinator sidebar component
  Firebase/dummyData/auth_export/accounts.json
  Firebase/dummyData/firebase-export-metadata.json
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/output-0
  Firebase/dummyData/firestore_export/firestore_export.overall_export_metadata
  Firebase/functions/package-lock.json
  Firebase/functions/package.json
  Firebase/functions/yarn.lock
  components/FormField.vue
  components/NavBar/NavBar.vue
  components/SearchSelect.vue
  package.json
  pages/admin.vue
  pages/admin/institutions.vue
  pages/admin/tournaments.vue
  pages/components.vue
  pages/coordinator.vue
  pages/coordinator/changepassword.vue
  pages/coordinator/draw.vue
  pages/coordinator/institutions.vue
  pages/coordinator/userinformation.vue
  pages/index.vue
  pages/signup.vue
  stores/admin.js
  stores/auth.js
  stores/institutions.js
  yarn.lock
Labels: backend, frontend, MVP

#184 I158 integrate firebase into team rego form
  Firebase/dummyData/auth_export/accounts.json
  Firebase/dummyData/firebase-export-metadata.json
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/output-0
  Firebase/dummyData/firestore_export/firestore_export.overall_export_metadata
  Firebase/firestore.rules
  components/HamburgerListItem.vue
  components/Header.vue
  components/NavBar/NavBar.vue
  components/SearchSelect.vue
  pages/coordinator.vue
  pages/coordinator/index.vue
  pages/coordinator/institutions.vue
  pages/coordinator/team-registration.vue
  pages/index.vue
  stores/admin.js
  stores/institutions.js
  stores/tournaments.js
Labels: MVP

#179 I171 fix table component
  components/Table.vue
Labels: frontend

#190 I187 Cleanup before production
  Firebase/dummyData/auth_export/accounts.json
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  Firebase/dummyData/firestore_export/all_namespaces/all_kinds/output-0
  Firebase/dummyData/firestore_export/firestore_export.overall_export_metadata
  components/Button.vue
  components/HamburgerListItem.vue
  components/HomePage/LevelButton.vue
  components/NavBar/HomeButton.vue
  components/NavBar/NavBar.vue
  components/Select.vue
  components/Table.vue
  pages/admin/adjudicators.vue
  pages/admin/index.vue
  pages/coordinator/changepassword.vue
  pages/coordinator/draw.vue
  pages/coordinator/index.vue
  pages/coordinator/team-registration.vue
  pages/coordinator/userinformation.vue
  pages/index.vue
  pages/login.vue
  stores/institutions.js
  stores/teams.js
  stores/tournaments.js
Labels: backend, bug, frontend

#199 removed links on admin page to venues and contacts
  pages/admin/index.vue
Labels: difficulty::easy, priority::high

#205 removed school code + clarified form fields
  pages/coordinator/institutions.vue
Labels: difficulty::easy, priority::high

#213 I208 resized DeleteDialog component
  components/DeleteDialog.vue
  components/Modal.vue
Labels: frontend

#197 I152 change position of add buttons
  components/SearchBar.vue
  pages/admin/contacts.vue
  pages/admin/index.vue
  pages/admin/institutions.vue
  pages/admin/signup-requests.vue
  pages/admin/tournaments.vue
  pages/admin/venues.vue
  stores/user.js
Labels: frontend, difficulty::easy, priority::low
